# name: attendance_app
# description: Attendance Management App with GPS & Selfie Verification
# publish_to: 'none'
# version: 1.0.0+1

# environment:
#   sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#     device_info_plus: ^9.0.0

#   # State Management
#   get: ^4.6.6

#   # HTTP
#   http: ^1.2.1

#   # Storage
#   shared_preferences: ^2.2.2

#   # Location
#   geolocator: ^11.0.0

#   # Camera & Image
#   image_picker: ^1.0.7
#   permission_handler: ^11.3.0

#   # UI
#   intl: ^0.19.0

#   cupertino_icons: ^1.0.6

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0

# flutter:
#   uses-material-design: true





name: attendance_app
description: Attendance Management App with GPS & Selfie Verification
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^9.0.0    # ← yahan aaya, flutter block ke baad

  # State Management
  get: ^4.6.6

  # HTTP
  http: ^1.2.1

  # Storage
  shared_preferences: ^2.2.2

  # Location
  geolocator: ^11.0.0

  # Camera & Image
  image_picker: ^1.0.7
  permission_handler: ^11.3.0

  # UI
  intl: ^0.19.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  